# Generated by Django 2.0.6 on 2018-08-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Articles', max_length=15)),
                ('header', models.CharField(default='Articles', max_length=30)),
                ('title', models.CharField(default='Articles', max_length=35)),
                ('sub_title', models.TextField(default='Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. proin eu mi. nulla tempus.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Contact', max_length=15)),
                ('header', models.CharField(default='Contact', max_length=30)),
                ('title', models.CharField(default='Où nous trouver', max_length=35)),
                ('sub_title', models.TextField(default="N'hésitez pas à nous contacter...", max_length=200)),
                ('sub_title2', models.TextField(default='... en nous laissant un message...', max_length=200)),
                ('sub_title3', models.TextField(default='... ou en passant directement nous voir.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EventsSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Events', max_length=15)),
                ('header', models.CharField(default='Galerie', max_length=30)),
                ('title', models.CharField(default='Derniers événements', max_length=35)),
                ('sub_title', models.TextField(default='Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. integer tincidunt ante vel ipsum. nam nulla.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Hero', max_length=15)),
                ('icon1', models.CharField(default='fab fa-cloudversify', max_length=20)),
                ('icon2', models.CharField(default='far fa-paint-brush', max_length=20)),
                ('icon3', models.CharField(default='far fa-compass', max_length=20)),
                ('title1', models.CharField(default='Odio lacinia', max_length=20)),
                ('title2', models.CharField(default='Vulputate in', max_length=20)),
                ('title3', models.CharField(default='Suspendisse donec', max_length=20)),
                ('text1', models.CharField(default='Praesent id massa id nisl venenatis lacinia. curabitur at ipsum ac tellus semper interdum.', max_length=200)),
                ('text2', models.CharField(default='Nulla tempus. quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', max_length=200)),
                ('text3', models.CharField(default='Integer ac neque. maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MainOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='PersonnalWebsiteForall', help_text='Nom du projet.', max_length=15)),
                ('name', models.CharField(default='MySite.', help_text='Nom du commerce.', max_length=15)),
                ('name_add', models.CharField(default='Forall', help_text='type de commerce.', max_length=9)),
                ('description', models.CharField(default='Hello world!', help_text='Très brève description.', max_length=30)),
                ('oppening', models.CharField(default='2016', help_text="Année d'ouverture.", max_length=4)),
                ('adress', models.CharField(default='awesome street', help_text='numéro + rue (12 rue des champs)', max_length=30)),
                ('city', models.CharField(blank=True, default='LeMonde', max_length=30, null=True)),
                ('post_code', models.CharField(blank=True, default='2000', max_length=4, null=True)),
                ('phone', models.CharField(blank=True, default='032-725-08-58', max_length=30, null=True)),
                ('mail', models.EmailField(blank=True, default='jrosk.ad@gmail.com', max_length=30, null=True)),
                ('facebook', models.CharField(blank=True, default='https://www.facebook.com/mcflysdinerneuchatel', max_length=1000, null=True)),
                ('tripadvisor', models.CharField(blank=True, default='https://www.tripadvisor.com/Restaurant_Review-g188066-d12069550-Reviews-McFly_s_Diner-Neuchatel.html', max_length=1000, null=True)),
                ('google', models.CharField(blank=True, default="https://www.google.ch/maps/place/McFly's+Diner+Neuch%C3%A2tel/@46.9922131,6.9248096,15z/data=!4m2!3m1!1s0x0:0x399ca68c2bcc87de?sa=X&ved=0ahUKEwiZ6cPbroPZAhWMOhQKHdR_Cz8Q_BIIggEwCg", max_length=1000, null=True)),
                ('twitter', models.CharField(blank=True, default='https://twitter.com/', max_length=1000, null=True)),
                ('instagram', models.CharField(blank=True, default='https://www.instagram.com/?hl=en', max_length=1000, null=True)),
                ('linkedin', models.CharField(blank=True, default='https://www.linkedin.com/', max_length=1000, null=True)),
                ('snapchat', models.CharField(blank=True, default='https://www.snapchat.com/', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('message', models.TextField(max_length=3000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_new', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PresentationSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Presentation', max_length=15)),
                ('title', models.CharField(default='Hello world!', max_length=35)),
                ('sub_title', models.TextField(default='Vestibulum ac est lacinia nisi venenatis tristique. morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', max_length=200)),
                ('text1', models.TextField(default='Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. nunc nisl. suspendisse ornare consequat lectus. in eleifend quam a odio. quisque id justo sit amet sapien dignissim vestibulum. vestibulum rutrum rutrum neque. suspendisse potenti. proin eu mi.', max_length=800)),
                ('text2', models.TextField(default='Etiam faucibus cursus urna. suspendisse potenti. mauris lacinia sapien quis libero. suspendisse ornare consequat lectus. maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. pellentesque viverra pede ac diam. vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; mauris viverra diam vitae quam. proin leo odio, porttitor id, consequat in, consequat ut, nulla. donec ut mauris eget massa tempor convallis.', max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='PromoSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Promo', max_length=15)),
                ('title', models.CharField(default='A title', max_length=35)),
                ('text', models.CharField(default='Integer a nibh. cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. vestibulum rutrum rutrum neque. suspendisse potenti.', max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Review', max_length=15)),
                ('title', models.CharField(default='Google Review', max_length=35)),
                ('sub_title', models.CharField(default='Ce que disent les gens de nous', max_length=200)),
                ('g_api', models.CharField(blank=True, default='AIzaSyAKrXyewXcDPgvG66yHBmm3vFZDoJDDS1M', max_length=1000, null=True)),
                ('g_place_id', models.CharField(blank=True, default='ChIJPwMEJQwCjkcRkmHo22dFFpo', max_length=1000, null=True)),
                ('g_review_all_url', models.CharField(blank=True, default='https://goo.gl/9XWfVB', max_length=1000, null=True)),
                ('g_review_new_url', models.CharField(blank=True, default='https://goo.gl/owSQ5r', max_length=1000, null=True)),
            ],
        ),
    ]
